require("jason.autocmds")
require("jason.options")
require("jason.keymaps")
require("jason.pluginspec")
spec("jason.mini")
-- spec("jason.colorscheme")
spec("jason.kanagawa") -- colorscheme
-- spec("jason.noirbuddy") -- colorscheme
-- spec("jason.everforest") -- colorscheme
spec("jason.autoformat")
spec("jason.autopairs")
spec("jason.lsp")
spec("jason.diffview")
-- spec("jason.nvim-tree")
spec("jason.neotree")
spec("jason.navic")
spec("jason.treesitter")
spec("jason.cmp")
spec("jason.misc")
spec("jason.telescope")
spec("jason.neogit")
spec("jason.project")
-- spec("jason.gitsigns")
require("jason.lazy")
